#配置端口和tomcat编码
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  #配置数据源
  datasource:
    druid:
      username: cmp
      password: dev2022
      url: jdbc:mariadb://14.18.33.148:3306/capability_management_platform?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true
      driver-class-name: org.mariadb.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      validation-query: SELECT 1
      #配置Druid监控
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid.gz
        login-password: druid.gz